import * as React from 'react';
import * as bp1 from "babel-polyfill";
import './tests/asyncLoaderTests';
import './tests/formsTest';
import './tests/dialogTests';
import './tests/bladesTests';
import './tests/utilsTests';
import './tests/listTests';
import './tests/mergeTests';
import * as history from 'history';
let h = history.createHashHistory();
(window as any)['_xx'] = bp1;